name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: namespace-profile-linux-default
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          package-manager-cache: false
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: |
            "npm"
            "gradle"
      - name: Setup gradle build cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle
      - name: "setup java"
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 21
          cache: "" # namespace handles this
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true # namespace handles this
      - run: ./gradlew --init-script=/tmp/init.gradle build
        working-directory: java
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: actions/upload-artifact@v4
        with:
          name: java-libs
          path: java/build/libs/

  e2e-tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            browser: chromium
          - os: ubuntu-24.04
            browser: firefox
          - os: macos-latest
            browser: webkit
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: java-libs
          path: java/build/libs/
      - run: npm ci
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - run: npm run test:e2e -- --project=${{ matrix.browser }}
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.os }}-${{ matrix.browser }}
          path: playwright-report/