name: Publish

on:
  push:
    branches: ["paper"]
  workflow_dispatch: # Manual run

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: namespace-profile-linux-default
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          package-manager-cache: false
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: |
            "npm"
            "gradle"
      - name: Setup gradle build cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true # namespace handles this
      - run: ./gradlew --init-script=/tmp/init.gradle build
        working-directory: java
      - run: npm ci
      - run: npm run build
      - run: npx wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
